name: pool-v2
version: 3.0.0
source: contracts
packages:
  - path: contracts/proxy/MaplePoolManagerFactory.sol
    contractName: MaplePoolManagerFactory
  - path: contracts/proxy/MaplePoolManagerInitializer.sol
    contractName: MaplePoolManagerInitializer
  - path: contracts/proxy/MaplePoolManagerMigrator.sol
    contractName: MaplePoolManagerMigrator
  - path: contracts/proxy/MaplePoolManagerWMMigrator.sol
    contractName: MaplePoolManagerWMMigrator
  - path: contracts/MaplePool.sol
    contractName: MaplePool
  - path: contracts/MaplePoolDelegateCover.sol
    contractName: MaplePoolDelegateCover
  - path: contracts/PoolDeployer.sol
    contractName: MaplePoolDeployer
  - path: contracts/MaplePoolManager.sol
    contractName: MaplePoolManager
customDescription: Pool Artifacts and ABIs
